/**
 * @aimeetx/sdk — Public API surface.
 *
 * This is the entry point for all consumers (web, desktop, mobile, 3rd-party).
 * Per ADR-005: the SDK is the single source of truth for all business logic.
 */

// tsyringe requires reflect-metadata to be imported BEFORE any other code.
// This MUST be the first import in the SDK entry point.
import 'reflect-metadata';

// Domain layer
export type { UseCase } from './domain/use-case.js';
export type { User } from './domain/model/user.js';
export type { UserRepository } from './domain/port/user-repository.js';
export { GetCurrentUserUseCase, type GetCurrentUserCommand } from './domain/usecase/get-current-user.js';

// Auth domain
export type {
  AuthCredentials,
  RegisterInput,
  Session,
  SessionStatus,
  AuthError,
} from './domain/model/auth.js';
export type { AuthRepository } from './domain/port/auth-repository.js';
export type { SecureTokenStorage } from './domain/port/secure-token-storage.js';
export type {
  UserLoggedInEvent,
  UserLoggedOutEvent,
  SessionExpiredEvent,
  SessionRefreshedEvent,
  AuthEvent,
} from './domain/event/auth-events.js';
export {
  LoginWithEmailUseCase,
  RegisterWithEmailUseCase,
  LoginAsGuestUseCase,
  LogoutUseCase,
  RefreshSessionUseCase,
} from './domain/usecase/auth-use-cases.js';

// Profile domain
export type {
  Theme,
  UserRole,
  AccountStatus,
  Presence,
  ProfileVisibility,
  UserProfile,
  UserPreferences,
  NotificationSettings,
  PrivacySettings,
  AccessibilitySettings,
  ProfileError,
} from './domain/model/profile.js';
export { AVATAR_CONSTRAINTS } from './domain/model/profile.js';
export type {
  AvatarUpload,
  AvatarUploadResult,
  ProfileUpdate,
  ProfileRepository,
} from './domain/port/profile-repository.js';
export type {
  ProfileUpdatedEvent,
  AvatarUpdatedEvent,
  AvatarRemovedEvent,
  ThemeChangedEvent,
  LanguageChangedEvent,
  TranslationLanguageChangedEvent,
  NotificationSettingsUpdatedEvent,
  PrivacySettingsUpdatedEvent,
  AccessibilitySettingsUpdatedEvent,
  PresenceChangedEvent,
  AccountDeactivatedEvent,
  ProfileEvent,
} from './domain/event/profile-events.js';
export {
  GetProfileUseCase,
  type GetProfileCommand,
  UpdateProfileUseCase,
  type UpdateProfileCommand,
  UploadAvatarUseCase,
  type UploadAvatarCommand,
  DeleteAvatarUseCase,
  type DeleteAvatarCommand,
  UpdateLanguagePreferenceUseCase,
  type UpdateLanguagePreferenceCommand,
  UpdateThemeUseCase,
  type UpdateThemeCommand,
  UpdateNotificationSettingsUseCase,
  type UpdateNotificationSettingsCommand,
  UpdatePrivacySettingsUseCase,
  type UpdatePrivacySettingsCommand,
  UpdateAccessibilitySettingsUseCase,
  type UpdateAccessibilitySettingsCommand,
  UpdatePresenceUseCase,
  type UpdatePresenceCommand,
  DeactivateAccountUseCase,
  type DeactivateAccountCommand,
} from './domain/usecase/profile-use-cases.js';

// Meeting domain
export type {
  MeetingStatus,
  ParticipantRole,
  ParticipantStatus,
  PermissionFlag,
  ConnectionState,
  NetworkQuality,
  RoomStatus,
  ResolutionStatus,
  RSVPStatus,
  ScheduleStatus,
  RecurrenceFrequency,
  WaitingRoomPolicy,
  AudioQuality,
  Meeting,
  MeetingSettings,
  Participant,
  MeetingRoom,
  RoomSettings,
  MeetingPermissions,
  ParticipantPermissionOverride,
  WaitingRoomEntry,
  MeetingInvitation,
  ScheduledMeeting,
  RecurrenceRule,
  ReminderSetting,
  ParticipantPresence,
  MeetingError,
} from './domain/model/meeting.js';
export {
  DEFAULT_MEETING_SETTINGS,
  DEFAULT_ROOM_SETTINGS,
  MEETING_CONSTRAINTS,
  canMuteOthers,
  canManageRoles,
  canAdmitOthers,
  canKickOthers,
  isPrivilegedRole,
} from './domain/model/meeting.js';
export type {
  CreateMeetingInput,
  MeetingUpdate,
  MeetingRepository,
  JoinMeetingInput,
  ParticipantRepository,
} from './domain/port/meeting-repository.js';
export type {
  MeetingCreatedEvent,
  MeetingStartedEvent,
  MeetingEndedEvent,
  MeetingUpdatedEvent,
  ParticipantJoinedEvent,
  ParticipantLeftEvent,
  ParticipantRoleChangedEvent,
  ParticipantMutedEvent,
  ParticipantHandRaisedEvent,
  ParticipantHandLoweredEvent,
  RoomCreatedEvent,
  RoomDestroyedEvent,
  RoomLockedEvent,
  RoomUnlockedEvent,
  RoomMutedAllEvent,
  RoomVideoDisabledEvent,
  RoomSettingsChangedEvent,
  GlobalPermissionsChangedEvent,
  SpeakPermissionGrantedEvent,
  SpeakPermissionRevokedEvent,
  WaitingRoomEnteredEvent,
  WaitingRoomAdmittedEvent,
  WaitingRoomDeniedEvent,
  InvitationCreatedEvent,
  InvitationRsvpUpdatedEvent,
  InvitationRevokedEvent,
  MeetingScheduledEvent,
  MeetingRescheduledEvent,
  MeetingCancelledEvent,
  MeetingReminderTriggeredEvent,
  ParticipantPresenceChangedEvent,
  ActiveSpeakerChangedEvent,
  NetworkQualityDegradedEvent,
  MeetingLifecycleEvent,
  ParticipantEvent,
  RoomEvent,
  PermissionEvent,
  WaitingRoomEvent,
  InvitationEvent,
  SchedulingEvent,
  PresenceEvent,
  MeetingEvent,
} from './domain/event/meeting-events.js';
export {
  CreateMeetingUseCase,
  type CreateMeetingCommand,
  GetMeetingUseCase,
  type GetMeetingCommand,
  UpdateMeetingUseCase,
  type UpdateMeetingCommand,
  StartMeetingUseCase,
  type StartMeetingCommand,
  EndMeetingUseCase,
  type EndMeetingCommand,
  JoinMeetingUseCase,
  type JoinMeetingCommand,
  LeaveMeetingUseCase,
  type LeaveMeetingCommand,
  MuteParticipantUseCase,
  type MuteParticipantCommand,
  ChangeParticipantRoleUseCase,
  type ChangeParticipantRoleCommand,
  RaiseHandUseCase,
  type RaiseHandCommand,
  LowerHandUseCase,
  type LowerHandCommand,
  ListParticipantsUseCase,
  type ListParticipantsCommand,
  ListMeetingsUseCase,
  type ListMeetingsCommand,
} from './domain/usecase/meeting-use-cases.js';

// Media domain
export type {
  // Branded IDs
  MediaSessionId,
  AudioSessionId,
  VideoSessionId,
  NetworkSessionId,
  ScreenShareSessionId,
  OrchestrationSessionId,
  MediaPlatformSessionId,
  MediaDeviceId,
  AudioStreamId,
  FrameId,
  PeerId,
  // States
  MediaSessionState,
  TransportState,
  RecoveryState,
  AudioState,
  VideoState,
  NetworkConnectionState,
  StreamType,
  ScreenShareState,
  CaptureSource,
  DeviceType,
  DeviceState,
  GlobalMediaState,
  PlatformSessionState,
  SessionType,
  PlatformParticipantRole,
  MediaNetworkQuality,
  // Value Objects
  AudioQualityProfile,
  AudioMetrics,
  ResolutionProfile,
  FrameRateProfile,
  EncodingProfile,
  VideoMetrics,
  StreamDescriptor,
  NetworkMetrics,
  RoutingProfile,
  CaptureProfile,
  CaptureRegion,
  ScreenMetrics,
  DeviceCapabilities,
  SessionCapabilities,
  SubsystemHealthSnapshot,
  OrchestrationPolicy,
  SessionPolicy,
  ParticipantProfile,
  // Aggregate Roots
  MediaSession,
  AudioSession,
  VideoSession,
  NetworkSession,
  PeerConnectionState,
  ScreenShareSession,
  MediaDevice,
  MediaOrchestrationSession,
  SubsystemStates,
  MediaPlatformSession,
} from './domain/model/media.js';
export {
  MEDIA_CONSTRAINTS,
  DEFAULT_AUDIO_QUALITY,
  DEFAULT_VIDEO_RESOLUTION,
  DEFAULT_VIDEO_FRAME_RATE,
  DEFAULT_VIDEO_ENCODING,
  DEFAULT_ORCHESTRATION_POLICY,
  DEFAULT_SESSION_POLICY,
  isMediaSessionTerminal,
  isMediaSessionActive,
  isAudioTerminal,
  isVideoTerminal,
  isNetworkTerminal,
  isNetworkConnected,
  isScreenShareTerminal,
  isDeviceSelectable,
  isGlobalMediaTerminal,
  isPlatformSessionTerminal,
  isPlatformHost,
  canPlatformManage,
} from './domain/model/media.js';
export type {
  // Repository Inputs
  CreateMediaSessionInput,
  CreateAudioSessionInput,
  CreateVideoSessionInput,
  CreateNetworkSessionInput,
  CreateScreenShareSessionInput,
  CreateMediaDeviceInput,
  CreateOrchestrationSessionInput,
  CreatePlatformSessionInput,
  AddPlatformParticipantInput,
  // Repository Ports
  MediaSessionRepository,
  AudioSessionRepository,
  VideoSessionRepository,
  NetworkSessionRepository,
  ScreenShareSessionRepository,
  MediaDeviceRepository,
  MediaOrchestrationSessionRepository,
  MediaPlatformSessionRepository,
} from './domain/port/media-repository.js';
export type {
  // Media Session Events
  MediaSessionCreatedEvent,
  MediaSessionReadyEvent,
  MediaSessionActivatedEvent,
  MediaSessionPausedEvent,
  MediaSessionRecoveredEvent,
  MediaSessionClosedEvent,
  // Audio Engine Events
  AudioSessionCreatedEvent,
  AudioProcessingStartedEvent,
  AudioQualityDegradedEvent,
  AudioRecoveredEvent,
  AudioSessionClosedEvent,
  AudioMetricsUpdatedEvent,
  // Video Engine Events
  VideoSessionCreatedEvent,
  VideoProcessingStartedEvent,
  VideoResolutionChangedEvent,
  VideoFrameRateChangedEvent,
  VideoQualityDegradedEvent,
  VideoRecoveredEvent,
  VideoMetricsUpdatedEvent,
  VideoSessionClosedEvent,
  // Network Layer Events
  NetworkSessionCreatedEvent,
  PeerConnectionEstablishedEvent,
  StreamNegotiationCompletedEvent,
  MediaNetworkQualityDegradedEvent,
  NetworkRecoveredEvent,
  PeerDisconnectedEvent,
  PeerReconnectedEvent,
  RoutingChangedEvent,
  NetworkSessionClosedEvent,
  // Screen Share Events
  ScreenShareSessionCreatedEvent,
  ScreenCaptureStartedEvent,
  ScreenSourceChangedEvent,
  ScreenRegionUpdatedEvent,
  ScreenQualityDegradedEvent,
  ScreenRecoveredEvent,
  ScreenMetricsUpdatedEvent,
  ScreenShareSessionClosedEvent,
  // Device Events
  DeviceSelectedEvent,
  DeviceChangedEvent,
  DeviceUnavailableEvent,
  DevicePermissionDeniedEvent,
  DeviceRecoveredEvent,
  // Orchestrator Events
  MediaOrchestrationStartedEvent,
  MediaGlobalStateChangedEvent,
  SubsystemCoordinationEvent,
  QualityPolicyAppliedEvent,
  RecoveryInitiatedEvent,
  RecoveryCompletedEvent,
  MediaOrchestrationStoppedEvent,
  // Platform Events
  MediaPlatformSessionCreatedEvent,
  MediaPlatformSessionStateChangedEvent,
  ParticipantRoleUpdatedEvent,
  SessionPolicyAppliedEvent,
  MediaPlatformSessionEndedEvent,
  // Event Unions
  MediaSessionEvent,
  AudioEngineEvent,
  VideoEngineEvent,
  NetworkLayerEvent,
  ScreenShareEvent,
  DeviceEvent,
  OrchestratorEvent,
  PlatformSessionEvent,
  MediaEvent,
} from './domain/event/media-events.js';
export {
  // Media Use Cases
  CreateMediaSessionUseCase,
  type CreateMediaSessionCommand,
  ActivateMediaSessionUseCase,
  type ActivateMediaSessionCommand,
  CloseMediaSessionUseCase,
  type CloseMediaSessionCommand,
  EnableCameraUseCase,
  type EnableCameraCommand,
  EnableMicrophoneUseCase,
  type EnableMicrophoneCommand,
  ToggleScreenShareUseCase,
  type ToggleScreenShareCommand,
  SelectDeviceUseCase,
  type SelectDeviceCommand,
  DiscoverDevicesUseCase,
  type DiscoverDevicesCommand,
  AdaptMediaQualityUseCase,
  type AdaptMediaQualityCommand,
  CreateOrchestrationSessionUseCase,
  type CreateOrchestrationSessionCommand,
  CreatePlatformSessionUseCase,
  type CreatePlatformSessionCommand,
  RegisterDeviceUseCase,
  type RegisterDeviceCommand,
  GetMediaSessionUseCase,
  type GetMediaSessionCommand,
  CreateNetworkSessionUseCase,
  type CreateNetworkSessionCommand,
} from './domain/usecase/media-use-cases.js';

// Data layer
export { HttpAuthRepository } from './data/http-auth-repository.js';
export { HttpProfileRepository } from './data/http-profile-repository.js';
export { WebSecureTokenStorage } from './data/web-secure-token-storage.js';

// DI
export { TOKENS, type Token } from './di/tokens.js';
export { initializeSdk, resetSdk, sdkContainer, type SdkConfig } from './di/container.js';
