'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { Button, colors, radius, spacing, typography } from '@aimeetx/ui';
import { useSession } from '@/lib/sdk/hooks';

const FEATURES = [
  { icon: '🌐', title: 'Live translation', body: 'Gemini-powered speech-to-speech translation in 50+ languages with real-time subtitles.' },
  { icon: '🤖', title: 'AI summaries', body: 'Automated action items, meeting summaries, and post-meeting reports generated by AI.' },
  { icon: '📚', title: 'Virtual classrooms', body: 'Built-in quizzes, attendance tracking, breakout rooms, and interactive learning tools.' },
  { icon: '🏢', title: 'Multi-tenant', body: 'Organization-level feature flags, role-based access control, and immutable audit logs.' },
  { icon: '🛡️', title: 'Enterprise security', body: 'End-to-end encryption, SOC 2 compliance, and granular permission controls.' },
  { icon: '📊', title: 'Analytics', body: 'Detailed meeting analytics, engagement metrics, and customizable reports.' },
];

const STEPS = [
  { num: '1', title: 'Create an account', body: 'Sign up in seconds with your email or as a guest.' },
  { num: '2', title: 'Start a meeting', body: 'Schedule or instantly start a meeting with custom settings.' },
  { num: '3', title: 'Collaborate in real time', body: 'Chat, share screens, translate, and use the whiteboard together.' },
  { num: '4', title: 'Review & analyze', body: 'Get AI summaries, recordings, and meeting analytics automatically.' },
];

export default function HomePage() {
  const router = useRouter();
  const [session] = useSession();

  useEffect(() => {
    if (session) router.replace('/dashboard');
  }, [session, router]);

  return (
    <div style={{ minHeight: '100vh', fontFamily: typography.fontFamily.sans, color: colors.light.text, backgroundColor: '#FFFFFF' }}>
      <Header />
      <HeroSection />
      <FeaturesSection />
      <HowItWorksSection />
      <CTASection />
      <Footer />
    </div>
  );
}

function Header() {
  return (
    <header style={{ position: 'sticky', top: 0, zIndex: 50, backgroundColor: 'rgba(255,255,255,0.9)', backdropFilter: 'blur(8px)', borderBottom: `1px solid ${colors.light.border}` }}>
      <nav style={{ maxWidth: 1200, margin: '0 auto', padding: `${spacing.md} ${spacing.xl}`, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: spacing.sm, textDecoration: 'none', color: colors.brand.primary, fontWeight: typography.fontWeight.bold, fontSize: typography.fontSize.xl }}>
          <Logo />
          AI MeetX
        </Link>
        <div style={{ display: 'flex', alignItems: 'center', gap: spacing.lg }}>
          <Link href="/login" style={{ textDecoration: 'none', color: colors.light.text, fontSize: typography.fontSize.sm, fontWeight: typography.fontWeight.medium }}>
            Sign in
          </Link>
          <Link href="/register" style={{ textDecoration: 'none' }}>
            <Button variant="primary" size="sm">Get started</Button>
          </Link>
        </div>
      </nav>
    </header>
  );
}

function HeroSection() {
  return (
    <section style={{ padding: `${spacing['3xl']} ${spacing.xl}`, textAlign: 'center', background: 'linear-gradient(135deg, #667EEA 0%, #764BA2 100%)', color: '#FFFFFF' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <div style={{ display: 'inline-flex', padding: `${spacing.xs} ${spacing.md}`, backgroundColor: 'rgba(255,255,255,0.2)', borderRadius: radius.full, fontSize: typography.fontSize.sm, marginBottom: spacing.lg, backdropFilter: 'blur(4px)' }}>
          AI-powered real-time collaboration platform
        </div>
        <h1 style={{ fontSize: 'clamp(2.5rem, 6vw, 4rem)', fontWeight: 800, marginBottom: spacing.md, lineHeight: 1.1 }}>
          Meet, translate, and collaborate — in any language.
        </h1>
        <p style={{ fontSize: typography.fontSize.lg, opacity: 0.9, marginBottom: spacing['2xl'], lineHeight: 1.6, maxWidth: 600, margin: '0 auto 2rem' }}>
          AI MeetX brings together real-time translation, intelligent summaries, virtual classrooms, and multi-tenant administration on a single SDK-first platform.
        </p>
        <div style={{ display: 'flex', gap: spacing.md, justifyContent: 'center' }}>
          <Link href="/register" style={{ textDecoration: 'none' }}>
            <button style={{ padding: `${spacing.md} ${spacing['2xl']}`, borderRadius: radius.md, border: 'none', backgroundColor: '#FFFFFF', color: '#764BA2', fontWeight: 700, fontSize: typography.fontSize.base, cursor: 'pointer', transition: 'transform 150ms ease' }}>
              Start free trial
            </button>
          </Link>
          <Link href="/login" style={{ textDecoration: 'none' }}>
            <button style={{ padding: `${spacing.md} ${spacing['2xl']}`, borderRadius: radius.md, border: '2px solid rgba(255,255,255,0.5)', backgroundColor: 'transparent', color: '#FFFFFF', fontWeight: 600, fontSize: typography.fontSize.base, cursor: 'pointer' }}>
              Sign in
            </button>
          </Link>
        </div>
        <p style={{ marginTop: spacing.xl, fontSize: typography.fontSize.sm, opacity: 0.7 }}>No credit card required · Free for up to 10 participants</p>
      </div>
    </section>
  );
}

function FeaturesSection() {
  return (
    <section style={{ padding: `${spacing['3xl']} ${spacing.xl}`, maxWidth: 1200, margin: '0 auto' }}>
      <h2 style={{ textAlign: 'center', fontSize: typography.fontSize['3xl'], fontWeight: 700, marginBottom: spacing.md }}>Everything you need for productive meetings</h2>
      <p style={{ textAlign: 'center', color: colors.light.textSecondary, marginBottom: spacing['2xl'], fontSize: typography.fontSize.base }}>
        From real-time translation to AI-powered insights — all in one platform.
      </p>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: spacing.lg }}>
        {FEATURES.map((f) => (
          <div key={f.title} style={{ padding: spacing.lg, backgroundColor: colors.light.surface, border: `1px solid ${colors.light.border}`, borderRadius: radius.lg, transition: 'transform 150ms ease, box-shadow 150ms ease' }}>
            <span style={{ fontSize: 32, marginBottom: spacing.sm, display: 'block' }}>{f.icon}</span>
            <h3 style={{ fontSize: typography.fontSize.lg, fontWeight: 600, marginBottom: spacing.sm, color: colors.brand.primary }}>{f.title}</h3>
            <p style={{ fontSize: typography.fontSize.sm, color: colors.light.textSecondary, lineHeight: 1.6, margin: 0 }}>{f.body}</p>
          </div>
        ))}
      </div>
    </section>
  );
}

function HowItWorksSection() {
  return (
    <section style={{ padding: `${spacing['3xl']} ${spacing.xl}`, backgroundColor: colors.light.surface }}>
      <div style={{ maxWidth: 1000, margin: '0 auto' }}>
        <h2 style={{ textAlign: 'center', fontSize: typography.fontSize['3xl'], fontWeight: 700, marginBottom: spacing['2xl'] }}>How it works</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: spacing.xl }}>
          {STEPS.map((s) => (
            <div key={s.num} style={{ textAlign: 'center' }}>
              <div style={{ width: 48, height: 48, borderRadius: '50%', backgroundColor: colors.brand.primary, color: '#FFFFFF', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: typography.fontSize.xl, fontWeight: 700, margin: '0 auto spacing.md' }}>
                {s.num}
              </div>
              <h3 style={{ fontSize: typography.fontSize.base, fontWeight: 600, marginBottom: spacing.xs }}>{s.title}</h3>
              <p style={{ fontSize: typography.fontSize.sm, color: colors.light.textSecondary, lineHeight: 1.5, margin: 0 }}>{s.body}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function CTASection() {
  return (
    <section style={{ padding: `${spacing['3xl']} ${spacing.xl}`, textAlign: 'center', background: 'linear-gradient(135deg, #764BA2 0%, #667EEA 100%)', color: '#FFFFFF' }}>
      <div style={{ maxWidth: 600, margin: '0 auto' }}>
        <h2 style={{ fontSize: 'clamp(1.8rem, 4vw, 2.5rem)', fontWeight: 700, marginBottom: spacing.md }}>Ready to transform your meetings?</h2>
        <p style={{ fontSize: typography.fontSize.base, opacity: 0.9, marginBottom: spacing.xl, lineHeight: 1.6 }}>
          Join thousands of teams already using AI MeetX for smarter, more inclusive collaboration.
        </p>
        <Link href="/register" style={{ textDecoration: 'none' }}>
          <button style={{ padding: `${spacing.md} ${spacing['2xl']}`, borderRadius: radius.md, border: 'none', backgroundColor: '#FFFFFF', color: '#764BA2', fontWeight: 700, fontSize: typography.fontSize.base, cursor: 'pointer', transition: 'transform 150ms ease' }}>
            Get started free
          </button>
        </Link>
      </div>
    </section>
  );
}

function Footer() {
  const footerLinks = {
    Product: ['Features', 'Pricing', 'Integrations', 'Changelog'],
    Company: ['About', 'Blog', 'Careers', 'Contact'],
    Legal: ['Privacy', 'Terms', 'Security', 'GDPR'],
  };

  return (
    <footer style={{ padding: `${spacing.xl} ${spacing.xl}`, backgroundColor: '#1F2937', color: '#9CA3AF' }}>
      <div style={{ maxWidth: 1200, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: spacing.xl }}>
        <div>
          <span style={{ color: '#FFFFFF', fontWeight: 600, fontSize: typography.fontSize.base }}>AI MeetX</span>
          <p style={{ fontSize: typography.fontSize.sm, marginTop: spacing.xs }}>AI-powered collaboration platform.</p>
        </div>
        {Object.entries(footerLinks).map(([category, links]) => (
          <div key={category}>
            <span style={{ color: '#FFFFFF', fontWeight: 600, fontSize: typography.fontSize.sm }}>{category}</span>
            <ul style={{ listStyle: 'none', padding: 0, marginTop: spacing.sm, display: 'flex', flexDirection: 'column', gap: spacing.xs }}>
              {links.map((l) => <li key={l} style={{ fontSize: typography.fontSize.sm, cursor: 'pointer' }}>{l}</li>)}
            </ul>
          </div>
        ))}
      </div>
      <div style={{ maxWidth: 1200, margin: '0 auto', marginTop: spacing.xl, paddingTop: spacing.lg, borderTop: '1px solid #374151', textAlign: 'center', fontSize: typography.fontSize.sm }}>
        &copy; {new Date().getFullYear()} AI MeetX. All rights reserved.
      </div>
    </footer>
  );
}

function Logo() {
  return (
    <svg width="24" height="24" viewBox="0 0 24 24" aria-hidden="true">
      <rect x="2" y="4" width="20" height="14" rx="3" fill={colors.brand.primary} />
      <circle cx="12" cy="11" r="3" fill="#FFFFFF" />
    </svg>
  );
}
